### ISSUE TITLE
Correlation with the official cmake-distribution

### ISSUE THREAD

**Issue by bam80** [pboettch/vim-cmake-syntax#21]
So what is the preferred way to get this stuff?
I see official repo here is much more recent:
https://cmake.org/gitweb?p=cmake.git;a=tree;f=Auxiliary/vim

**Comment by pboettch** [comment]
Yep, it's been some time since I synchronized things. I will check it right away.

**Comment by pboettch** [comment]
https://gitlab.kitware.com/cmake/cmake/-/merge_requests/5438

**Comment by bfrg** [comment]
Since you're the maintainer of the [cmake](https://github.com/vim/vim/blob/master/runtime/syntax/cmake.vim) syntax file that is shipped with Vim, can you update that one, too? The current version is from 2017. A few weeks ago I asked one of the other maintainers mentioned in the header of the syntax file (Dimitri Merejkowsky) to do that. But he said that he doesn't use CMake anymore. You might want to update the list of maintainers as well.
